version: '3.3'
services:

  motor_project:
    build: ./motor_project
    container_name: motor_project
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./motor_project/:/app/
    ports:
      - '8000:8000'
    restart: always

  coffee_project:
    build: ./coffee_project
    container_name: coffee_project
    command: uvicorn main_cof:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./coffee_project/:/app/
    ports:
      - '8001:8001'
    restart: always
    
  mongo_db:
    image: mongo
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - "27017:27017"  